dbbuku/dbbuku/Controllers/BukuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace dbbuku.Controllers
{
    public class BukuController : Controller
    {
        // GET: Buku
        public ActionResult Index()
        {
            return View();
        }
    }
}

dbbuku/dbbuku/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/Content/datatables/select.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/Content/datatables/buttons.bootstrap4.min.css" rel="stylesheet" />

    <script src="~/Scripts/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/datatables/js/dataTables.select.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script src="~/Scripts/js.js"></script>

    <script>
        $.rootDir = '@Url.Content("~/")';
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @{if (User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Halaman Buku", "Index", "Buku")</li>
                            if (User.IsInRole("User"))
                            {
                                <li>@Html.ActionLink("Transaksi", "Index", "Transaksi")</li>
                            }
                            else
                            {
                                <li>@Html.ActionLink("Laporan", "Index", "Laporan")</li>
                            }
                        }
                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>


    @RenderSection("scripts", required: false)
</body>
</html>